apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: nginx
          volumeMounts:
            - mountPath: /opt/cont1/
              name: devops

        - name: cont2
          image: nginx
          command: ["/bin/bash", "-c", "while true; do echo hi how are you; sleep 10; done"]
          volumeMounts:
            - mountPath: /opt/cont2/
              name: devops

      volumes:
        - name: devops
          persistentVolumeClaim:
            claimName: pvc-ebs
