---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      name: mytemplate2
      labels:
        app: uber    
    spec:
      containers:
        - name: cont3
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: myvolume
              mountPath: /usr/share/nginx/html

      volumes:
        - name: myvolume
          configMap: 
            name: cm3

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc2
spec:
  type: NodePort
  selector:
    app: uber
  ports:
    - port: 80
      targetPort: 80  
