---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpfile-1
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      name: mytemplate
      labels:
        app: zomato
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80    
